app:
  api_host: 0.0.0.0
  api_port: 8000
  debug: true
  log_level: info  # Options: 'debug', 'info', 'warning', 'error', 'critical'

logging:
  log_to_console: true
  log_to_file: true
  log_file_path: logs/application.log
  log_file_mode: a  # Options: 'a' for append, 'w' for overwrite
  max_bytes: 10485760  # 10 MB for rotating logs
  backup_count: 5
  formatter: '[%(asctime)s] %(levelname)s - %(name)s - %(message)s'
  datefmt: '%Y-%m-%d %H:%M:%S'